sudo: required

dist: trusty

language: cpp

compiler: gcc

before_install:
- sudo apt-get update  -qq
- sudo apt-get install -qq libsqlite3-dev libnetcdf-dev python python-dev swig tcl8.5-dev
script:
- uname -a
- which qmake
- gcc --version
- g++ --version
- mkdir build
- cd build ; cmake .. ; make
#- sudo make install
#- make check 
