language: cpp

compiler: gcc

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev

install:
- uname -a
- which qmake
- qmake --help
- qmake --version
- gcc --version
- g++ --version
- pwd

script:
- qmake -project
- qmake QADCModules.pro
- make
