sudo: required
dist: trusty
language: cpp
compiler: gcc
install: export CXX="g++-5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libsqlite3-dev
      - libnetcdf-dev
      - python
      - python-dev
      - swig3.0
      - tcl8.5-dev
      - lcov
      - netcdf-bin
      - libgdal-dev
      - cmake

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info '*/thirdparty/*' --output-file coverage.info # filter thirdparty code
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

script:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - mkdir build; cd build; cmake -DCOVERAGE=ON -DBUILD_TESTS=ON ..
  - cd build; make -j 4
  - cd build; CTEST_OUTPUT_ON_FAILURE=1 make test
  # Export CC and CXX to tell cmake which compiler to use
  - cd build; cmake -DCOVERAGE=ON -DBUILD_TESTS=ON -DUSE_CXX14=ON ..
  - cd build; CTEST_OUTPUT_ON_FAILURE=1 make test
